project:
  type: book
  output-dir: build

lang: nl

book:
  title: "Cyberboswachters"
  author: "Tim Dams"
  navbar:
    background: dark
    left:
      - text: "Slides"
        href: slides/overzicht.qmd
      - text: "Slides (EN)"
        href: slides/en/index.qmd
      - text: "PDF"
        icon: file-pdf
        href: Cyberboswachters.pdf
  chapters:
    - index.qmd
    - content/0_het_security_landschap/les1_wordtheterger.md
    - content/0_het_security_landschap/2_basicsec.md
    - content/1_cryptografie/basics.md
    - content/3_netwerk_security/wifi.md
    - content/1_cryptografie/authenticatie.md
    - content/5_iot/iotintro.md
  appendices:
    - content/0_het_security_landschap/3_gdpr.md
    - content/appendix/darkweb.md
    - content/appendix/awareness.md
    - content/appendix/meerweten.md
    - content/appendix/bronnen.md
    - slides/overzicht.qmd
    - slides/en/index.qmd

bibliography: references.bib

format:
  html:
    theme: [sandstone, brand, custom.scss]
    toc: true
    lightbox: true
  typst:
    mainfont: "Arial"
    papersize: a4
    section-numbering: "1.1"
    margin:
      x: 2.5cm
      y: 3cm
      