project:
  type: website
  output-dir: ../build/slides
  render:
    - "*.qmd"
    - "en/*.qmd"
    - "!overzicht.qmd"
    - "!en/index.qmd"

website:
  title: "Cyberboswachters – Slides"

format:
  revealjs:
    theme: [default, _extensions/grantmcdermott/clean/clean.scss]
    lang: nl
    slide-number: true
    logo: ../cover.png
    transition: slide