name: Build and Publish Book

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/extra
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk add --no-cache python3 py3-pip
          pip install pandoc-latex-environment --break-system-packages

      - name: Build Book
        run: |
          chmod +x Manuscript/build.sh
          ./Manuscript/build.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Manuscript/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
